version: '3.8'

services:
  search-api:
    build:
      context: ../repository-search-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
